export const API_URL = 'https://api.unsplash.com';
export const API_URL_TOKEN = 'https://unsplash.com/oauth/token?';
export const API_URL_AUTH = 'https://unsplash.com/oauth/authorize?';
export const ACCESS_KEY = 'ZKaI3gYXugTgPwRTrNz9kGZDHwPnzrqY8IQWHHySSEY';
export const SECRET_KEY = '4JRNvHkP7ULicA1CkzislWds8LXqQ6AfOqHaE9wqk24';
export const RESPONSE_TYPE = 'code';
export const REDIRECT_URI = 'http://localhost:3000';
export const SCOPE = 'public read_user read_photos write_likes';
export const GRANT_TYPE = 'authorization_code';
